worker_processes auto;

events {
    worker_connections 1024;
}

http {
    upstream user-service {
        server localhost:8081;
    }

    upstream auth-service {
        server localhost:8082;
    }

    upstream post-service {
        server localhost:8083;
    }

    server {
        listen 8080;
        server_name localhost;

        add_header 'Access-Control-Allow-Origin' 'localhost:5173';
        add_header 'Access-Control-Allow-Methods' 'GET, POST, HEAD, OPTIONS';
        
        if ($request_method = 'OPTIONS') {
            add_header 'Access-Control-Allow-Credentials' 'true';
            add_header 'Access-Control-Allow-Headers' 'DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type';
            add_header 'Content-Type' 'application/json';
            add_header 'Content-Length' 0;
            return 204;
        }

        location /api/v1/auth {
            proxy_pass http://auth-service;
        }

        location /api/v1/profiles {
            proxy_pass http://user-service;
        }

        location /api/v1/users {
            proxy_pass http://post-service;
        }
    }
}