// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.0
// source: get_posts.proto

package post

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GetBatchPostsFeature_Execute_FullMethodName = "/post.GetBatchPostsFeature/Execute"
)

// GetBatchPostsFeatureClient is the client API for GetBatchPostsFeature service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GetBatchPostsFeatureClient interface {
	Execute(ctx context.Context, in *GetBatchPostsReq, opts ...grpc.CallOption) (*GetBatchPostsResp, error)
}

type getBatchPostsFeatureClient struct {
	cc grpc.ClientConnInterface
}

func NewGetBatchPostsFeatureClient(cc grpc.ClientConnInterface) GetBatchPostsFeatureClient {
	return &getBatchPostsFeatureClient{cc}
}

func (c *getBatchPostsFeatureClient) Execute(ctx context.Context, in *GetBatchPostsReq, opts ...grpc.CallOption) (*GetBatchPostsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBatchPostsResp)
	err := c.cc.Invoke(ctx, GetBatchPostsFeature_Execute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetBatchPostsFeatureServer is the server API for GetBatchPostsFeature service.
// All implementations must embed UnimplementedGetBatchPostsFeatureServer
// for forward compatibility.
type GetBatchPostsFeatureServer interface {
	Execute(context.Context, *GetBatchPostsReq) (*GetBatchPostsResp, error)
	mustEmbedUnimplementedGetBatchPostsFeatureServer()
}

// UnimplementedGetBatchPostsFeatureServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGetBatchPostsFeatureServer struct{}

func (UnimplementedGetBatchPostsFeatureServer) Execute(context.Context, *GetBatchPostsReq) (*GetBatchPostsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method Execute not implemented")
}
func (UnimplementedGetBatchPostsFeatureServer) mustEmbedUnimplementedGetBatchPostsFeatureServer() {}
func (UnimplementedGetBatchPostsFeatureServer) testEmbeddedByValue()                              {}

// UnsafeGetBatchPostsFeatureServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GetBatchPostsFeatureServer will
// result in compilation errors.
type UnsafeGetBatchPostsFeatureServer interface {
	mustEmbedUnimplementedGetBatchPostsFeatureServer()
}

func RegisterGetBatchPostsFeatureServer(s grpc.ServiceRegistrar, srv GetBatchPostsFeatureServer) {
	// If the following call panics, it indicates UnimplementedGetBatchPostsFeatureServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GetBatchPostsFeature_ServiceDesc, srv)
}

func _GetBatchPostsFeature_Execute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBatchPostsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GetBatchPostsFeatureServer).Execute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GetBatchPostsFeature_Execute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GetBatchPostsFeatureServer).Execute(ctx, req.(*GetBatchPostsReq))
	}
	return interceptor(ctx, in, info, handler)
}

// GetBatchPostsFeature_ServiceDesc is the grpc.ServiceDesc for GetBatchPostsFeature service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GetBatchPostsFeature_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "post.GetBatchPostsFeature",
	HandlerType: (*GetBatchPostsFeatureServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Execute",
			Handler:    _GetBatchPostsFeature_Execute_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "get_posts.proto",
}
