// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.0
// source: get_posts.proto

package post

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NodeType int32

const (
	NodeType_NODE_TYPE_UNSPECIFIED NodeType = 0
	NodeType_NODE_TYPE_TEXT        NodeType = 1
	NodeType_NODE_TYPE_MENTION     NodeType = 2
	NodeType_NODE_TYPE_HASHTAG     NodeType = 3
)

// Enum value maps for NodeType.
var (
	NodeType_name = map[int32]string{
		0: "NODE_TYPE_UNSPECIFIED",
		1: "NODE_TYPE_TEXT",
		2: "NODE_TYPE_MENTION",
		3: "NODE_TYPE_HASHTAG",
	}
	NodeType_value = map[string]int32{
		"NODE_TYPE_UNSPECIFIED": 0,
		"NODE_TYPE_TEXT":        1,
		"NODE_TYPE_MENTION":     2,
		"NODE_TYPE_HASHTAG":     3,
	}
)

func (x NodeType) Enum() *NodeType {
	p := new(NodeType)
	*p = x
	return p
}

func (x NodeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NodeType) Descriptor() protoreflect.EnumDescriptor {
	return file_get_posts_proto_enumTypes[0].Descriptor()
}

func (NodeType) Type() protoreflect.EnumType {
	return &file_get_posts_proto_enumTypes[0]
}

func (x NodeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NodeType.Descriptor instead.
func (NodeType) EnumDescriptor() ([]byte, []int) {
	return file_get_posts_proto_rawDescGZIP(), []int{0}
}

type MediaType int32

const (
	MediaType_MEDIA_TYPE_UNSPECIFIED MediaType = 0
	MediaType_MEDIA_TYPE_IMAGE       MediaType = 1
	MediaType_MEDIA_TYPE_VIDEO       MediaType = 2
)

// Enum value maps for MediaType.
var (
	MediaType_name = map[int32]string{
		0: "MEDIA_TYPE_UNSPECIFIED",
		1: "MEDIA_TYPE_IMAGE",
		2: "MEDIA_TYPE_VIDEO",
	}
	MediaType_value = map[string]int32{
		"MEDIA_TYPE_UNSPECIFIED": 0,
		"MEDIA_TYPE_IMAGE":       1,
		"MEDIA_TYPE_VIDEO":       2,
	}
)

func (x MediaType) Enum() *MediaType {
	p := new(MediaType)
	*p = x
	return p
}

func (x MediaType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MediaType) Descriptor() protoreflect.EnumDescriptor {
	return file_get_posts_proto_enumTypes[1].Descriptor()
}

func (MediaType) Type() protoreflect.EnumType {
	return &file_get_posts_proto_enumTypes[1]
}

func (x MediaType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MediaType.Descriptor instead.
func (MediaType) EnumDescriptor() ([]byte, []int) {
	return file_get_posts_proto_rawDescGZIP(), []int{1}
}

type Visibility int32

const (
	Visibility_VISIBILITY_UNSPECIFIED Visibility = 0
	Visibility_VISIBILITY_PRIVATE     Visibility = 1
	Visibility_VISIBILITY_PUBLIC      Visibility = 2
	Visibility_VISIBILITY_FRIEND      Visibility = 3
)

// Enum value maps for Visibility.
var (
	Visibility_name = map[int32]string{
		0: "VISIBILITY_UNSPECIFIED",
		1: "VISIBILITY_PRIVATE",
		2: "VISIBILITY_PUBLIC",
		3: "VISIBILITY_FRIEND",
	}
	Visibility_value = map[string]int32{
		"VISIBILITY_UNSPECIFIED": 0,
		"VISIBILITY_PRIVATE":     1,
		"VISIBILITY_PUBLIC":      2,
		"VISIBILITY_FRIEND":      3,
	}
)

func (x Visibility) Enum() *Visibility {
	p := new(Visibility)
	*p = x
	return p
}

func (x Visibility) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Visibility) Descriptor() protoreflect.EnumDescriptor {
	return file_get_posts_proto_enumTypes[2].Descriptor()
}

func (Visibility) Type() protoreflect.EnumType {
	return &file_get_posts_proto_enumTypes[2]
}

func (x Visibility) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Visibility.Descriptor instead.
func (Visibility) EnumDescriptor() ([]byte, []int) {
	return file_get_posts_proto_rawDescGZIP(), []int{2}
}

type GetBatchPostsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []int64                `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBatchPostsReq) Reset() {
	*x = GetBatchPostsReq{}
	mi := &file_get_posts_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBatchPostsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBatchPostsReq) ProtoMessage() {}

func (x *GetBatchPostsReq) ProtoReflect() protoreflect.Message {
	mi := &file_get_posts_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBatchPostsReq.ProtoReflect.Descriptor instead.
func (*GetBatchPostsReq) Descriptor() ([]byte, []int) {
	return file_get_posts_proto_rawDescGZIP(), []int{0}
}

func (x *GetBatchPostsReq) GetIds() []int64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

type Post struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	AuthorId      int64                  `protobuf:"varint,2,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	Visibility    Visibility             `protobuf:"varint,3,opt,name=visibility,proto3,enum=post.Visibility" json:"visibility,omitempty"`
	Contents      []*Content             `protobuf:"bytes,4,rep,name=contents,proto3" json:"contents,omitempty"`
	ThumbnailId   string                 `protobuf:"bytes,6,opt,name=thumbnail_id,json=thumbnailId,proto3" json:"thumbnail_id,omitempty"`
	Medias        []*Media               `protobuf:"bytes,7,rep,name=medias,proto3" json:"medias,omitempty"`
	Mentions      []int64                `protobuf:"varint,8,rep,packed,name=mentions,proto3" json:"mentions,omitempty"`
	HashTags      []string               `protobuf:"bytes,9,rep,name=hash_tags,json=hashTags,proto3" json:"hash_tags,omitempty"`
	LikeCount     int32                  `protobuf:"varint,10,opt,name=like_count,json=likeCount,proto3" json:"like_count,omitempty"`
	MediaCount    int32                  `protobuf:"varint,11,opt,name=media_count,json=mediaCount,proto3" json:"media_count,omitempty"`
	CommentCount  int32                  `protobuf:"varint,12,opt,name=comment_count,json=commentCount,proto3" json:"comment_count,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Post) Reset() {
	*x = Post{}
	mi := &file_get_posts_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Post) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Post) ProtoMessage() {}

func (x *Post) ProtoReflect() protoreflect.Message {
	mi := &file_get_posts_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Post.ProtoReflect.Descriptor instead.
func (*Post) Descriptor() ([]byte, []int) {
	return file_get_posts_proto_rawDescGZIP(), []int{1}
}

func (x *Post) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Post) GetAuthorId() int64 {
	if x != nil {
		return x.AuthorId
	}
	return 0
}

func (x *Post) GetVisibility() Visibility {
	if x != nil {
		return x.Visibility
	}
	return Visibility_VISIBILITY_UNSPECIFIED
}

func (x *Post) GetContents() []*Content {
	if x != nil {
		return x.Contents
	}
	return nil
}

func (x *Post) GetThumbnailId() string {
	if x != nil {
		return x.ThumbnailId
	}
	return ""
}

func (x *Post) GetMedias() []*Media {
	if x != nil {
		return x.Medias
	}
	return nil
}

func (x *Post) GetMentions() []int64 {
	if x != nil {
		return x.Mentions
	}
	return nil
}

func (x *Post) GetHashTags() []string {
	if x != nil {
		return x.HashTags
	}
	return nil
}

func (x *Post) GetLikeCount() int32 {
	if x != nil {
		return x.LikeCount
	}
	return 0
}

func (x *Post) GetMediaCount() int32 {
	if x != nil {
		return x.MediaCount
	}
	return 0
}

func (x *Post) GetCommentCount() int32 {
	if x != nil {
		return x.CommentCount
	}
	return 0
}

func (x *Post) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Post) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type Media struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	MediaId       string                 `protobuf:"bytes,2,opt,name=media_id,json=mediaId,proto3" json:"media_id,omitempty"`
	Type          MediaType              `protobuf:"varint,3,opt,name=type,proto3,enum=post.MediaType" json:"type,omitempty"`
	DisplayOrder  int32                  `protobuf:"varint,4,opt,name=display_order,json=displayOrder,proto3" json:"display_order,omitempty"`
	Width         int32                  `protobuf:"varint,5,opt,name=width,proto3" json:"width,omitempty"`
	Height        int32                  `protobuf:"varint,6,opt,name=height,proto3" json:"height,omitempty"`
	Duration      *durationpb.Duration   `protobuf:"bytes,7,opt,name=duration,proto3" json:"duration,omitempty"`
	Size          int64                  `protobuf:"varint,8,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Media) Reset() {
	*x = Media{}
	mi := &file_get_posts_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Media) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Media) ProtoMessage() {}

func (x *Media) ProtoReflect() protoreflect.Message {
	mi := &file_get_posts_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Media.ProtoReflect.Descriptor instead.
func (*Media) Descriptor() ([]byte, []int) {
	return file_get_posts_proto_rawDescGZIP(), []int{2}
}

func (x *Media) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Media) GetMediaId() string {
	if x != nil {
		return x.MediaId
	}
	return ""
}

func (x *Media) GetType() MediaType {
	if x != nil {
		return x.Type
	}
	return MediaType_MEDIA_TYPE_UNSPECIFIED
}

func (x *Media) GetDisplayOrder() int32 {
	if x != nil {
		return x.DisplayOrder
	}
	return 0
}

func (x *Media) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *Media) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *Media) GetDuration() *durationpb.Duration {
	if x != nil {
		return x.Duration
	}
	return nil
}

func (x *Media) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type Content struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          NodeType               `protobuf:"varint,1,opt,name=type,proto3,enum=post.NodeType" json:"type,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Content) Reset() {
	*x = Content{}
	mi := &file_get_posts_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Content) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Content) ProtoMessage() {}

func (x *Content) ProtoReflect() protoreflect.Message {
	mi := &file_get_posts_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Content.ProtoReflect.Descriptor instead.
func (*Content) Descriptor() ([]byte, []int) {
	return file_get_posts_proto_rawDescGZIP(), []int{3}
}

func (x *Content) GetType() NodeType {
	if x != nil {
		return x.Type
	}
	return NodeType_NODE_TYPE_UNSPECIFIED
}

func (x *Content) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type GetBatchPostsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Posts         []*Post                `protobuf:"bytes,1,rep,name=posts,proto3" json:"posts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBatchPostsResp) Reset() {
	*x = GetBatchPostsResp{}
	mi := &file_get_posts_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBatchPostsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBatchPostsResp) ProtoMessage() {}

func (x *GetBatchPostsResp) ProtoReflect() protoreflect.Message {
	mi := &file_get_posts_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBatchPostsResp.ProtoReflect.Descriptor instead.
func (*GetBatchPostsResp) Descriptor() ([]byte, []int) {
	return file_get_posts_proto_rawDescGZIP(), []int{4}
}

func (x *GetBatchPostsResp) GetPosts() []*Post {
	if x != nil {
		return x.Posts
	}
	return nil
}

var File_get_posts_proto protoreflect.FileDescriptor

const file_get_posts_proto_rawDesc = "" +
	"\n" +
	"\x0fget_posts.proto\x12\x04post\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\"$\n" +
	"\x10GetBatchPostsReq\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\x03R\x03ids\"\xec\x03\n" +
	"\x04Post\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\tauthor_id\x18\x02 \x01(\x03R\bauthorId\x120\n" +
	"\n" +
	"visibility\x18\x03 \x01(\x0e2\x10.post.VisibilityR\n" +
	"visibility\x12)\n" +
	"\bcontents\x18\x04 \x03(\v2\r.post.ContentR\bcontents\x12!\n" +
	"\fthumbnail_id\x18\x06 \x01(\tR\vthumbnailId\x12#\n" +
	"\x06medias\x18\a \x03(\v2\v.post.MediaR\x06medias\x12\x1a\n" +
	"\bmentions\x18\b \x03(\x03R\bmentions\x12\x1b\n" +
	"\thash_tags\x18\t \x03(\tR\bhashTags\x12\x1d\n" +
	"\n" +
	"like_count\x18\n" +
	" \x01(\x05R\tlikeCount\x12\x1f\n" +
	"\vmedia_count\x18\v \x01(\x05R\n" +
	"mediaCount\x12#\n" +
	"\rcomment_count\x18\f \x01(\x05R\fcommentCount\x129\n" +
	"\n" +
	"created_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xf5\x01\n" +
	"\x05Media\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x19\n" +
	"\bmedia_id\x18\x02 \x01(\tR\amediaId\x12#\n" +
	"\x04type\x18\x03 \x01(\x0e2\x0f.post.MediaTypeR\x04type\x12#\n" +
	"\rdisplay_order\x18\x04 \x01(\x05R\fdisplayOrder\x12\x14\n" +
	"\x05width\x18\x05 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x06 \x01(\x05R\x06height\x125\n" +
	"\bduration\x18\a \x01(\v2\x19.google.protobuf.DurationR\bduration\x12\x12\n" +
	"\x04size\x18\b \x01(\x03R\x04size\"A\n" +
	"\aContent\x12\"\n" +
	"\x04type\x18\x01 \x01(\x0e2\x0e.post.NodeTypeR\x04type\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\"5\n" +
	"\x11GetBatchPostsResp\x12 \n" +
	"\x05posts\x18\x01 \x03(\v2\n" +
	".post.PostR\x05posts*g\n" +
	"\bNodeType\x12\x19\n" +
	"\x15NODE_TYPE_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eNODE_TYPE_TEXT\x10\x01\x12\x15\n" +
	"\x11NODE_TYPE_MENTION\x10\x02\x12\x15\n" +
	"\x11NODE_TYPE_HASHTAG\x10\x03*S\n" +
	"\tMediaType\x12\x1a\n" +
	"\x16MEDIA_TYPE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10MEDIA_TYPE_IMAGE\x10\x01\x12\x14\n" +
	"\x10MEDIA_TYPE_VIDEO\x10\x02*n\n" +
	"\n" +
	"Visibility\x12\x1a\n" +
	"\x16VISIBILITY_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12VISIBILITY_PRIVATE\x10\x01\x12\x15\n" +
	"\x11VISIBILITY_PUBLIC\x10\x02\x12\x15\n" +
	"\x11VISIBILITY_FRIEND\x10\x032T\n" +
	"\x14GetBatchPostsFeature\x12<\n" +
	"\aExecute\x12\x16.post.GetBatchPostsReq\x1a\x17.post.GetBatchPostsResp\"\x00B%Z#github.com/htan06/Moments/grpc/postb\x06proto3"

var (
	file_get_posts_proto_rawDescOnce sync.Once
	file_get_posts_proto_rawDescData []byte
)

func file_get_posts_proto_rawDescGZIP() []byte {
	file_get_posts_proto_rawDescOnce.Do(func() {
		file_get_posts_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_get_posts_proto_rawDesc), len(file_get_posts_proto_rawDesc)))
	})
	return file_get_posts_proto_rawDescData
}

var file_get_posts_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_get_posts_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_get_posts_proto_goTypes = []any{
	(NodeType)(0),                 // 0: post.NodeType
	(MediaType)(0),                // 1: post.MediaType
	(Visibility)(0),               // 2: post.Visibility
	(*GetBatchPostsReq)(nil),      // 3: post.GetBatchPostsReq
	(*Post)(nil),                  // 4: post.Post
	(*Media)(nil),                 // 5: post.Media
	(*Content)(nil),               // 6: post.Content
	(*GetBatchPostsResp)(nil),     // 7: post.GetBatchPostsResp
	(*timestamppb.Timestamp)(nil), // 8: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),   // 9: google.protobuf.Duration
}
var file_get_posts_proto_depIdxs = []int32{
	2,  // 0: post.Post.visibility:type_name -> post.Visibility
	6,  // 1: post.Post.contents:type_name -> post.Content
	5,  // 2: post.Post.medias:type_name -> post.Media
	8,  // 3: post.Post.created_at:type_name -> google.protobuf.Timestamp
	8,  // 4: post.Post.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 5: post.Media.type:type_name -> post.MediaType
	9,  // 6: post.Media.duration:type_name -> google.protobuf.Duration
	0,  // 7: post.Content.type:type_name -> post.NodeType
	4,  // 8: post.GetBatchPostsResp.posts:type_name -> post.Post
	3,  // 9: post.GetBatchPostsFeature.Execute:input_type -> post.GetBatchPostsReq
	7,  // 10: post.GetBatchPostsFeature.Execute:output_type -> post.GetBatchPostsResp
	10, // [10:11] is the sub-list for method output_type
	9,  // [9:10] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_get_posts_proto_init() }
func file_get_posts_proto_init() {
	if File_get_posts_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_get_posts_proto_rawDesc), len(file_get_posts_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_get_posts_proto_goTypes,
		DependencyIndexes: file_get_posts_proto_depIdxs,
		EnumInfos:         file_get_posts_proto_enumTypes,
		MessageInfos:      file_get_posts_proto_msgTypes,
	}.Build()
	File_get_posts_proto = out.File
	file_get_posts_proto_goTypes = nil
	file_get_posts_proto_depIdxs = nil
}
